blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

import post

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
]

blog/post/urls.py
from django.urls import path

from post import views

app_name = 'post'
urlpatterns = [
    path('new/', views.new, name='new'),
    path('list/', views.list, name='list'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('comment_delete/<int:id>/<int:comment_id>', views.comment_delete, name='comment_delete'),
]

blog/post/models.py
from django.db import models

# Create your models here.


class Posting(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now=True)

blog/post/views.py
from datetime import timedelta
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from post.models import Posting, Comment


def new(request):
    if request.method == 'POST':
        title = request.POST.get('title', '')
        content = request.POST.get('content', '')
        posting = Posting.objects.create(title = title, content = content)
        posting.updated_at = False
        posting.save()
        return redirect('post:detail', posting.id)
    else :
        return render(request, 'post/new.html')

def list(request):
    postings = Posting.objects.all()
    # ts = Posting.objects.filter(title__in=postings)
    q = request.GET.get('q', '')
    print(q)
    if q:
        postings = postings.filter(title__icontains=q)

    return render(request, 'post/list.html', {'postings':postings, 'q':q})

def detail(request, id):
    posting = get_object_or_404(Posting, id=id)
    if posting.updated_at - posting.created_at >= timedelta(seconds=1):
        updated = True
    else :
        updated = False
    comments = Comment.objects.filter(posting=posting).order_by('-id')
    if request.method == 'POST':
        content = request.POST.get('comment_content','')
        comment = Comment.objects.create(posting=posting, content=content)
        return redirect('post:detail', posting.id)
    else:
        return render(request, 'post/detail.html', {'posting':posting, 'comments':comments, 'updated':updated})

def edit(request, id):
    posting = get_object_or_404(Posting, id=id)
    if request.method == 'POST':
        posting.title = request.POST.get('title', '')
        posting.content = request.POST.get('content', '')
        posting.save()
        return redirect('post:detail', id)
    else :
        return render(request, 'post/edit.html', {'posting':posting})

def delete(request, id):
    posting = get_object_or_404(Posting, id=id)
    posting.delete()
    return redirect('post:list')

def comment_delete(request, id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect('post:detail', id)

blog/post/templates/post/base_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans|Nanum+Gothic+Coding&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/397f20b135.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <style>
        * {
            color : black;
        }

        i {
            color : #E40043;
        }

        * {
            font-family: 'Nanum Gothic Coding', monospace;
        }

        h5 {
            font-weight: normal;
        }

        h1 {
            font-family: 'Black Han Sans', sans-serif;
        }
    </style>
</head>
<body>

{#<div style="width:100%; height: 220px; overflow: hidden;">#}
{#    <img src="http://prography.org/img/seo.png" alt="" style="margin-top:-150px; width:100%; height: 500px;">#}
{#        </div>#}

<br/>
<div class="container">
    <div class="row">
    <div class="col-1" style="display: inline-block;"></div>
    <div class="col-10" style="display: inline-block;"><a href="{% url 'post:list' %}"><h1 style="color: #E40043;">Prography 5th django</h1></a></div>
    </div>
</div>

<br/>

<div class="container">
    <div class="row">
        <div class="col-1" style="display: inline-block;"></div>
        <div class="col-10" style="display: inline-block;">
            {% block content %}
            {% endblock %}
        </div>
        <div class="col-1" style="display: inline-block;"></div>
    </div>
</div>


</body>
</html>

blog/post/templates/post/detail.html
{% extends 'post/base_post.html' %}

{% block content %}
<h3 style="font-weight: bold;">{{ posting.title }}</h3>
<small>{{ posting.created_at }} {% if updated %}(최종수정:{{ posting.updated_at }}){% endif %}</small>
<hr/>
<h5 style="white-space: pre-line; line-height: 1.5em;">{{ posting.content }}</h5>

<br/>

<a href="{% url 'post:edit' posting.id %}"><button>수정</button></a>
<a href="{% url 'post:delete' posting.id %}"><button>삭제</button></a>


    <br/>
    <br/>
    <br/>
    <br/>
    <br/>

    <h4>Comments</h4>
    <hr/>

    <form action="" method="POST">
    {% csrf_token %}
    <textarea required style="width:90% ; height: 100px;" type="text" name="comment_content"></textarea>
    <button style="float: right;" type="submit">제출</button>
</form>
    <hr/>

     {% for comment in comments %}
        <p style="white-space: pre;">{{ comment.content }}</p>
         <small>{{ comment.created_at }} |
         <a href="{% url 'post:comment_delete' posting.id comment.id %}">삭제</a></small>
        <hr/>
    {% endfor %}

<br/>
<br/>
<br/>

<a href="{% url 'post:list' %}"><i class="fas fa-home"></i></a>

{% endblock %}

blog/post/templates/post/edit.html
{% extends 'post/base_post.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    <input required style="width:90%;" type="text" name="title" value="{{ posting.title }}">
    <hr/>
    <textarea required style="width:90%; height: 300px;" type="text" name="content">{{ posting.content }}</textarea>

    <br/>

    <button type="submit">제출</button>
</form>

<br/>
    <br/>
<br/>

<a href="{% url 'post:list' %}"><i class="fas fa-home"></i></a>
{% endblock %}

blog/post/templates/post/list.html
{% extends 'post/base_post.html' %}

{% block content %}

    <div class="jumbotron jumbotron-fluid" style="position: relative;">
        <div class="container">
            <h1 class="display-4">프로그라피 게시판</h1>
            <p class="lead">프로그라피 5기 장고 게시판입니다.</p>
        </div>
        <a href="{% url 'post:new' %}" style="position:absolute; right:20px; bottom:20px;"><i class="fas fa-plus"></i></a>

    </div>

    <div class="search_bar" style="text-align: right">
        <form action="" method="get">
            <input type="text" name="q" value="{{ q }}" style="height: 30px;"/>
            <button type="submit" style="border:transparent; background-color: transparent;">
                <i class="fas fa-search"></i>
            </button>
        </form>
    </div>

    <br/>

    {% if q %}
        <div style="text-align:center;">'{{ q }}' 검색 결과입니다.<a href="{% url 'post:list' %}" style="color: #E40043;">전체 목록 보기</a>
        </div>
        <br/>
    {% endif %}


    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col" style="width:60%;">제목</th>
      <th scope="col">작성일</th>
    </tr>
  </thead>
  <tbody>
  {% for posting in postings %}
      <tr>
      <th scope="row">{{ forloop.counter }}</th>
          <td><a href="{% url 'post:detail' posting.id %}" style="color: #E40043; font-weight: bold;">{{ posting.title }}</a></td>
      <td>{{ posting.created_at }}</td>
    </tr>
        {% endfor %}
  </tbody>
</table>

    <br/>
    <br/>
    <br/>


{% endblock %}

blog/post/templates/post/new.html
{% extends 'post/base_post.html' %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <input required style="width:90%;" type="text" name="title"/>
    <hr/>
    <textarea required style="width:90%; height: 300px;" type="text" name="content"></textarea>

    <br/>

    <button type="submit">제출</button>



</form>

<br/>
    <br/>
<br/>

<a href="{% url 'post:list' %}"><i class="fas fa-home"></i></a>

{% endblock %}